In [1]:
import os
import sys

import pandas as pd
pd.options.display.max_columns = 999
import sqlalchemy as sqla
from sqlalchemy import create_engine

DB_URI = os.getenv('CD_DWH')
engine = create_engine(DB_URI)

In [2]:
QUERY = """
select
    distinct regexp_replace(lower(recipient_candidate_name), '[^a-z ]', '', 'g') as clean_name
from trg_analytics.candidate_contributions
"""
with engine.begin() as conn:
    results = pd.read_sql(QUERY, conn)

results.head(100)

              clean_name
0                   None
1              west tony
2          krouse thomas
3              smith mel
4           denney ralph
5         perez v manuel
6        pacheco gayle e
7         smith robert w
8         leyva connie m
9            brough bill
10       firebaugh marco
11           eng michael
12          murray kevin
13        quinones pearl
14       gallegos martin
15        miller david d
16            kramer dan
17           choi steven
18       carcione john p
19          reilly emily
20            mann chris
21          nickel wiley
22        young steven r
23         barton john h
24    pullenmiles robert
25         wyland mark b
26        price curren d
27         peterson pete
28        kinney richard
29        hanley kevin j
..                   ...
70    gonzales juan luis
71     schaupp charles e
72             buck jill
73   nickel iii george w
74                le van
75            dutton bob
76        pirozzi elia v
77          holden chris
78          lara ricardo
79          mastin james
80         salas jr rudy
81          marquez luis
82  roditis konstantinos
83     caserta dominic j
84         do cong thanh
85       monteith dick j
86    frazier jr james l
87        parker chris r
88           wicks buffy
89        gardner m dean
90         tran kim ngoc
91           aroner dion
92         loo kenneth j
93          parra pete h
94          kennedy john
95      fernandez joanne
96          mahmood asif
97        taylor zachary
98       bradford steven
99     pfeiler lori holt

[100 rows x 1 columns]

In [4]:
from fuzzywuzzy import fuzz

size = len(results["clean_name"])

for i in range(size):
    name = results["clean_name"][i]
    for j in range(i + 1, size):
        test = results["clean_name"][j]
        fuz = fuzz.ratio(name, test)
        if fuz >= 85:
            print("{}% Similar {} to {} at {} and {}".format(fuz, name, test, i, j))

92% Similar leyva connie m to leyva connie at 8 and 1017
87% Similar eng michael to fong michael at 11 and 1307
93% Similar young steven r to young steven ray at 22 and 64
88% Similar young steven r to young steve at 22 and 170
85% Similar barton john h to burton john l at 23 and 719
92% Similar price curren d to price curren at 26 and 432
93% Similar peterson pete to peterson pete n at 27 and 268
93% Similar murray cynthia l to murray cynthia at 30 and 51
85% Similar torlakson mae to torlakson tom at 34 and 843
96% Similar papan virginia to papan virgina at 37 and 699
90% Similar wood carl w to wood carl at 40 and 1040
89% Similar song paul to fong paul at 54 and 154
86% Similar olberg r keith to olberg keith r at 58 and 892
95% Similar diaz manny to diaz mannny at 59 and 1179
94% Similar schaupp charles e to schaupp charles at 71 and 381
92% Similar marquez luis to marquez luis h at 81 and 332
86% Similar caserta dominic j to caserta jr dominic at 83 and 1299
92% Similar gardner m dean to gardner dean at 89 and 411
93% Similar breyer michael to breyer michael c at 100 and 236
85% Similar steel michelle to park steel michelle at 104 and 304
88% Similar dantona jr jim to dantona jim at 110 and 1483
88% Similar miles jr lawrence w to miles  lawrence at 111 and 882
92% Similar gaines beth b to gaines beth at 124 and 1095
91% Similar nava pedro to nava pedro i at 133 and 1014
93% Similar topalian rita to topalian rita h at 139 and 959
94% Similar hernandez manuel to hernandez manuel p at 140 and 683
93% Similar dymally mervyn m to dymally mervyn at 143 and 528
89% Similar galvan isaac to galvan  isaac j at 145 and 751
88% Similar roesch jean to roesch jean dr at 158 and 233
92% Similar medina jose j to medina jose at 163 and 1045
94% Similar mc pherson bruce to mc pherson bruce a at 165 and 1122
92% Similar torres norma j to torres norma at 167 and 420
88% Similar quintero frank to quintero iii frank at 172 and 1332
93% Similar allen michael j to allen michael at 173 and 747
92% Similar logue daniel to logue daniel r at 182 and 478
89% Similar hallinan thomas to hallinan tom at 183 and 522
94% Similar vasquez melinda to vasquez melinda k at 187 and 288
89% Similar monville iii lou to monville iii louis g at 204 and 1506
93% Similar medina abigail to medina abigail m at 209 and 514
95% Similar von szeliski heidi j to von szeliski heidi at 212 and 1262
93% Similar yamada mariko m to yamada mariko at 223 and 1068
87% Similar ledford james c to medford james d at 228 and 521
92% Similar morris gwen l to morris gwen at 229 and 715
90% Similar mc donald kristine l to mcdonald kristine lang at 230 and 1134
85% Similar smith marianne bopp to smith marianne at 235 and 498
93% Similar runner george c to runner george at 237 and 639
87% Similar gaines edward ted to gaines edward at 242 and 850
94% Similar gaines edward ted to gaines edward t at 242 and 1290
93% Similar voorakkara sid c to voorakkara sid at 243 and 1146
92% Similar jones linda k to jones linda at 263 and 472
94% Similar aanestad samuel to aanestad samuel m at 265 and 1101
93% Similar keating janice e to keating janice at 266 and 638
94% Similar blumenfeld andrew to blumenfeld andrew j at 291 and 548
90% Similar diridon jr rodney to diridon rodney at 293 and 331
92% Similar chabot paul to chabot paul r at 294 and 962
95% Similar villaraigosa antonio to villaraigosa antonio r at 296 and 1022
97% Similar mcgarry nellie to mc garry nellie at 309 and 722
92% Similar davis saundra to david saundra at 316 and 338
95% Similar armenta christopher to armenta christopher r at 325 and 612
91% Similar gould john to gould john s at 333 and 1443
94% Similar furutani warren t to furutani warren at 337 and 526
87% Similar hunter tricia to hunter tricia rae at 350 and 758
90% Similar brown jr willie l to brown willie l at 351 and 674
88% Similar silva  james w to silva james at 356 and 583
94% Similar phares ana ventura to phares ann ventura at 370 and 431
92% Similar meuser mark p to meuser mark at 373 and 1536
93% Similar willis warren to willis warren p at 383 and 696
94% Similar thiesen timothy to thiesen timothy a at 385 and 1410
85% Similar thiesen timothy to thiesen tim at 385 and 1438
92% Similar bosetti rick to bosetti rick a at 390 and 761
93% Similar horton jerome e to horton jerome at 391 and 1372
96% Similar yee  betty t to yee betty t at 395 and 468
89% Similar kiraly virginia c to kiraly virginia chang at 397 and 550
93% Similar wilson michael to wilson michael l at 408 and 1147
91% Similar popp elena i to popp elena at 412 and 911
85% Similar pan richard to polanco richard at 414 and 729
97% Similar mc carthy kevin to mc carty kevin at 426 and 486
93% Similar mc carthy kevin to mccarty kevin at 426 and 1449
90% Similar chavez edward to chavez edward ed at 427 and 1191
87% Similar akili gregory to akili greg at 434 and 1257
88% Similar harrington michael to harrison michael at 439 and 1074
94% Similar gonzalez lorena to gonzalez lorena s at 445 and 1419
92% Similar forsch glen to forsch glen r at 446 and 1407
95% Similar hosterman jennifer to hosterman jennifer a at 447 and 881
93% Similar keene richard to keene richard j at 449 and 573
92% Similar warner russ h to warner russ at 453 and 594
88% Similar uranga tonia r to uranga tonia reyes at 471 and 742
96% Similar mc carty kevin to mccarty kevin at 486 and 1449
89% Similar hallinan tom to hallinan jr tom at 522 and 873
93% Similar anderson joel to anderson joel c at 534 and 1556
92% Similar benoit john to benoit john j at 540 and 1168
92% Similar vargas juan to vargas juan c at 541 and 1161
88% Similar aguirre richard to gutierrez richard at 556 and 797
92% Similar hanson mark to hanson mark n at 590 and 787
90% Similar cook paul j to cook paul at 596 and 1333
92% Similar mullin gene to mullin gene r at 597 and 768
91% Similar glaab paul g to glaab paul at 608 and 1241
91% Similar dutra john a to dutra john at 611 and 860
97% Similar quintero andre to quintero andres at 621 and 1323
92% Similar ong jennifer h to ong jennifer at 640 and 831
97% Similar de saulnier mark to desaulnier mark at 641 and 1073
88% Similar angelides philip n to angelides phil at 642 and 969
85% Similar caplane ronnie to caplane ronnie gail at 651 and 1091
94% Similar chavez christina to chavez christine at 662 and 1316
94% Similar canciamilla laura to canciamilla laura s at 665 and 1217
93% Similar kraft gregory to kraft gregory a at 673 and 1504
93% Similar wyman phillip to wyman phillip d at 678 and 949
92% Similar alby barbara to alby barbara j at 688 and 967
86% Similar wakim sam to wakim samuel at 689 and 938
87% Similar papan virgina to papan gina at 699 and 891
93% Similar hammond lauren r to hammond lauren at 707 and 1531
90% Similar maccarley mark to mac carley mark j at 708 and 1514
90% Similar kim young to kim young o at 726 and 1472
93% Similar hodges sherry to hodges sherry m at 733 and 1318
94% Similar craffey matthew g to craffey matthew at 736 and 906
91% Similar king david a to king david at 759 and 897
93% Similar rubio michael j to rubio michael at 781 and 1554
95% Similar antonovich michael to antonovich michael d at 785 and 1413
88% Similar pacheco robert bob to pacheco robert at 786 and 1357
93% Similar connolly damon m to connolly damon at 789 and 795
86% Similar leyes mark a to leyes mak at 805 and 1521
88% Similar baca jr jr joe to baca jr joe at 808 and 1226
92% Similar miller gary g to miller gary at 836 and 942
90% Similar ebenstein jeff to ebenstein jeffery at 840 and 1441
91% Similar young joel b to young joel at 844 and 1057
93% Similar gaines edward to gaines edward t at 850 and 1290
92% Similar wapner alan d to wapner alan at 863 and 1426
90% Similar pena john to pena john j at 910 and 1225
90% Similar campbell john to campbell john bt at 924 and 1360
95% Similar petersonmore diana l to petersonmore diana at 941 and 1542
91% Similar mcfadden bradley to mc fadden bradley j at 943 and 1189
92% Similar gipson mike to gipson mike a at 958 and 1115
91% Similar gutierez lydia ann to gutierrez lydia a at 971 and 1547
93% Similar armenta david w to armenta david at 974 and 1034
94% Similar mc iver barbara to mc iver barbara g at 984 and 1002

94% Similar shoemaker brandon k to shoemaker brandon at 1009 and 1543
87% Similar umberg tom to umberg thomas at 1011 and 1097
92% Similar vidal thomas h to vidal thomas at 1032 and 1123
91% Similar davenport ii robert to davenport robert at 1039 and 1174
93% Similar lutness carole l to lutness carole at 1052 and 1306
93% Similar umberg thomas j to umberg thomas at 1054 and 1097
90% Similar aldana jr manuel to aldana manuel at 1070 and 1526
93% Similar sanders joanne to sanders joanne b at 1102 and 1356
90% Similar munn john to munn john r at 1111 and 1199
93% Similar groper richard p to groper richard at 1113 and 1114
92% Similar atkins toni g to atkins toni at 1119 and 1389
85% Similar camejo peter m to camejo peter miguel at 1150 and 1324
96% Similar mccann john to mc cann john at 1170 and 1240
94% Similar jacobi veronica to jacobi veronica s at 1202 and 1205
92% Similar houston guy to houston guy s at 1230 and 1491
93% Similar walker prophet to walker prophet l at 1249 and 1519
91% Similar wesson herman j to wesson jr herman j at 1269 and 1353
92% Similar hodge jason t to hodge jason at 1287 and 1395
94% Similar snodgrass donna j to snodgrass donna at 1378 and 1541
93% Similar ortiz deborah to ortiz deborah v at 1386 and 1434
88% Similar martinez diane to martinez   diane j at 1501 and 1548
96% Similar garamedi john to garamendi john at 1525 and 1545